### ISSUE TITLE
Closing project when a map is selected crashes Editor since GTK+ 3.4

### ISSUE THREAD

**Issue by ghost** [EasyRPG/Editor-GTK#11]
Steps to reproduce:
- Open a project
- Select a map on the map tree
- Click the close project button

Editor will crash with segmentation fault.

Tested With GTK+ 3.4.0 and 3.4.1.
Crashes with both Vala 0.14 and 0.16 versions.

**Comment by Falc** [comment]
With GTK 3.2 there is no crash, it closes correctly.

Does it display any error message that helps to find out what is causing that crash?

**Comment by ghost** [comment]
console messages before crashing:

```
** (easyrpg-editor:5988): CRITICAL **: map_get_tileset: assertion `self != NULL' failed
** (easyrpg-editor:5988): CRITICAL **: tile_palette_drawing_area_load_tileset: assertion `tileset != NULL' failed
```

Stack Trace:

```
Hilo 1 (Thread 0xb7fdd840 (LWP 5988)):
#0  0x00858c89 in cairo_image_surface_get_width () from /usr/lib/i386-linux-gnu/libcairo.so.2
#1  0x08067b8e in tile_palette_drawing_area_set_layer (self=0x81ece08, layer=LAYER_TYPE_UPPER) at drawingarea_tile_palette.c:684
#2  0x0805c57e in main_controller_load_map (self=0x8196410, map_id=2) at controller_main.c:2930
#3  0x0805c3c7 in main_controller_on_map_selected (self=0x8196410, map_id=2) at controller_main.c:2861
#4  0x08083422 in _main_controller_on_map_selected_maptree_tree_view_map_selected (_sender=0x819c450, map_id=2, self=0x8196410) at view_main_window.c:399
#5  0x00906711 in g_cclosure_marshal_VOID(int0_t, void) () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#6  0x00904727 in ?? () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#7  0x0091da29 in g_signal_emit_valist () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#8  0x0091e8af in g_signal_emit_by_name () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#9  0x0807bcaf in maptree_tree_view_on_change (self=0x819c450) at treeview_maptree.c:413
#10 0x0807b1f9 in _maptree_tree_view_on_change_gtk_tree_view_cursor_changed (_sender=0x819c450, self=0x819c450) at treeview_maptree.c:135
#11 0x009061ec in g_cclosure_marshal_VOID__VOID () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#12 0x00904484 in g_closure_invoke () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#13 0x009160d9 in ?? () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#14 0x0091e2dc in g_signal_emit_valist () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#15 0x0091e453 in g_signal_emit () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#16 0x003e3256 in ?? () from /usr/lib/i386-linux-gnu/libgtk-3.so.0
#17 0x003e6587 in ?? () from /usr/lib/i386-linux-gnu/libgtk-3.so.0
#18 0x00907333 in g_cclosure_marshal_VOID__BOXED () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#19 0x00904484 in g_closure_invoke () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#20 0x009160d9 in ?? () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#21 0x0091e2dc in g_signal_emit_valist () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#22 0x0091e453 in g_signal_emit () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#23 0x003bfe1a in gtk_tree_model_row_deleted () from /usr/lib/i386-linux-gnu/libgtk-3.so.0
#24 0x003d0bd0 in gtk_tree_store_remove () from /usr/lib/i386-linux-gnu/libgtk-3.so.0
#25 0x003d0d09 in ?? () from /usr/lib/i386-linux-gnu/libgtk-3.so.0
#26 0x003d0cd0 in ?? () from /usr/lib/i386-linux-gnu/libgtk-3.so.0
#27 0x003d0cd0 in ?? () from /usr/lib/i386-linux-gnu/libgtk-3.so.0
#28 0x003d204d in gtk_tree_store_clear () from /usr/lib/i386-linux-gnu/libgtk-3.so.0
#29 0x0807babd in maptree_tree_view_clear (self=0x819c450) at treeview_maptree.c:376
#30 0x0805b48e in main_controller_close_project (self=0x8196410) at controller_main.c:2486
#31 0x080833a9 in _main_controller_close_project_gtk_action_activate (_sender=0x80cd5c0, self=0x8196410) at view_main_window.c:369
#32 0x009061ec in g_cclosure_marshal_VOID__VOID () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#33 0x00904484 in g_closure_invoke () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#34 0x009160d9 in ?? () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#35 0x0091e2dc in g_signal_emit_valist () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#36 0x0091e453 in g_signal_emit () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#37 0x001b48f6 in ?? () from /usr/lib/i386-linux-gnu/libgtk-3.so.0
#38 0x001b508d in gtk_action_activate () from /usr/lib/i386-linux-gnu/libgtk-3.so.0
#39 0x003a968e in ?? () from /usr/lib/i386-linux-gnu/libgtk-3.so.0
#40 0x00906243 in g_cclosure_marshal_VOID__VOIDv () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#41 0x00904727 in ?? () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#42 0x0091da29 in g_signal_emit_valist () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#43 0x0091e453 in g_signal_emit () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#44 0x001de12a in gtk_button_clicked () from /usr/lib/i386-linux-gnu/libgtk-3.so.0
#45 0x001df820 in ?? () from /usr/lib/i386-linux-gnu/libgtk-3.so.0
#46 0x009061ec in g_cclosure_marshal_VOID__VOID () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#47 0x009032fd in ?? () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#48 0x00904484 in g_closure_invoke () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#49 0x00916535 in ?? () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#50 0x0091e2dc in g_signal_emit_valist () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#51 0x0091e453 in g_signal_emit () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#52 0x001dda66 in ?? () from /usr/lib/i386-linux-gnu/libgtk-3.so.0
#53 0x002b80d1 in ?? () from /usr/lib/i386-linux-gnu/libgtk-3.so.0
#54 0x00902db7 in ?? () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#55 0x00904727 in ?? () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#56 0x0091da29 in g_signal_emit_valist () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#57 0x0091e453 in g_signal_emit () from /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
#58 0x0040233b in ?? () from /usr/lib/i386-linux-gnu/libgtk-3.so.0
#59 0x002b5a6f in ?? () from /usr/lib/i386-linux-gnu/libgtk-3.so.0
#60 0x002b7c90 in gtk_main_do_event () from /usr/lib/i386-linux-gnu/libgtk-3.so.0
#61 0x0060a60c in ?? () from /usr/lib/i386-linux-gnu/libgdk-3.so.0
#62 0x00633878 in ?? () from /usr/lib/i386-linux-gnu/libgdk-3.so.0
#63 0x0098ccda in g_main_context_dispatch () from /lib/i386-linux-gnu/libglib-2.0.so.0
#64 0x0098d0e5 in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#65 0x0098d52b in g_main_loop_run () from /lib/i386-linux-gnu/libglib-2.0.so.0
#66 0x002b6e25 in gtk_main () from /usr/lib/i386-linux-gnu/libgtk-3.so.0
#67 0x08068e77 in editor_main (args=0xbffff8b4, args_length1=1) at editor.c:268
#68 0x08068ed7 in main (argc=1, argv=0xbffff8b4) at editor.c:278

Hilo 3 (Thread 0xb1fffb40 (LWP 5992)):
#0  0x00132416 in __kernel_vsyscall ()
#1  0x00b1b380 in poll () from /lib/i386-linux-gnu/libc.so.6
#2  0x0099aa3b in g_poll () from /lib/i386-linux-gnu/libglib-2.0.so.0
#3  0x0098d06e in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#4  0x0098d52b in g_main_loop_run () from /lib/i386-linux-gnu/libglib-2.0.so.0
#5  0x007380ea in ?? () from /usr/lib/i386-linux-gnu/libgio-2.0.so.0
#6  0x009b0673 in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#7  0x00df9d4c in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#8  0x00b29ace in clone () from /lib/i386-linux-gnu/libc.so.6

Hilo 4 (Thread 0xb15ffb40 (LWP 5993)):
#0  0x00132416 in __kernel_vsyscall ()
#1  0x00b1b380 in poll () from /lib/i386-linux-gnu/libc.so.6
#2  0x0099aa3b in g_poll () from /lib/i386-linux-gnu/libglib-2.0.so.0
#3  0x0098d06e in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#4  0x0098d52b in g_main_loop_run () from /lib/i386-linux-gnu/libglib-2.0.so.0
#5  0x01251134 in ?? () from /usr/lib/i386-linux-gnu/gio/modules/libdconfsettings.so
#6  0x009b0673 in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#7  0x00df9d4c in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#8  0x00b29ace in clone () from /lib/i386-linux-gnu/libc.so.6

Hilo 11 (Thread 0xaddf8b40 (LWP 6000)):
#0  0x00132416 in __kernel_vsyscall ()
#1  0x00dfdd13 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib/i386-linux-gnu/libpthread.so.0
#2  0x00b37434 in pthread_cond_timedwait () from /lib/i386-linux-gnu/libc.so.6
#3  0x009cc8a0 in g_cond_wait_until () from /lib/i386-linux-gnu/libglib-2.0.so.0
#4  0x009600b9 in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#5  0x009608de in g_async_queue_timeout_pop () from /lib/i386-linux-gnu/libglib-2.0.so.0
#6  0x009b0f3c in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#7  0x009b0673 in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#8  0x00df9d4c in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#9  0x00b29ace in clone () from /lib/i386-linux-gnu/libc.so.6
```
